#!/bin/busybox ash
/bin/busybox --install -s
mkdir sys proc tmp usr
busybox mount -t devtmpfs devtmpfs /dev
busybox mount -t sysfs sysfs /sys
busybox mount -t proc procfs /proc
busybox mount -t tmpfs tmpfs /tmp 
busybox ash
