#!/bin/busybox ash
busybox mkdir sys proc tmp usr usr/bin/ sbin usr/sbin
busybox /bin/busybox --install -s
busybox mount -t devtmpfs devtmpfs /dev
busybox mount -t sysfs sysfs /sys
busybox mount -t proc procfs /proc
busybox mount -t tmpfs tmpfs /tmp 
mkdir dev/pts
busybox mount -o bind dev/pts dev/pts

./bin/sysinfo

#mkdir -pv etc/dropbear
#echo create ssh key
bin/dropbearmulti dropbearkey -t rsa -s 4096 -f etc/dropbear/dropbear_rsa_host_key > etc/dropbear/dropbear_rsa_host_key_pub
#echo finish

dropbearmulti dropbear
busybox ash

